ShopPhone/Models/Home/PhoneIndexViewModel.cs
namespace ShopPhone.Models.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class PhoneIndexViewModel
    {
        public int Id { get; set; }

        public string Brand { get; set; }

        public string Model { get; set; }

        public string ImageUrl { get; set; }

        public int Year { get; set; }
    }
}

ShopPhone/Controllers/HomeController.cs
namespace ShopPhone.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using ShopPhone.Services.Phones;
    using ShopPhone.Services.Phones.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class HomeController : Controller
    {
        private readonly IPhoneService phone;
        private readonly IMemoryCache cache;

        public HomeController(IMemoryCache cache, IPhoneService phone)
        {
            this.cache = cache;
            this.phone = phone;
        }

        public IActionResult Index()
        {
            const string latestPhonesCacheKey = "LatestPhonesCacheKey";

            var phoneCache = this.cache.Get<List<LatestPhoneServiceModel>>(latestPhonesCacheKey);

            if (phoneCache == null)
            {
                phoneCache = this.phone
                    .Latest()
                    .ToList();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(10));

                this.cache.Set(latestPhonesCacheKey, phoneCache, cacheOptions);
            }

            return View(phoneCache);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ShopPhone/Controllers/PhonesController.cs
namespace ShopPhone.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ShopPhone.Infrastructure;
    using ShopPhone.Models;
    using ShopPhone.Models.Phones;
    using ShopPhone.Services.Owners;
    using ShopPhone.Services.Phones;

    using static WebConstants;

    public class PhonesController : Controller
    {
        private readonly IPhoneService phones;
        private readonly IOwnerService owners;
        private readonly IMapper mapper;

        public PhonesController(IPhoneService phones,
            IOwnerService owners,
            IMapper mapper)
        {
            this.phones = phones;
            this.owners = owners;
            this.mapper = mapper;
        }

        public IActionResult All([FromQuery] AllPhonesQueryModel query)
        {
            var allPhones = this.phones.All(
                query.Brand,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllPhonesQueryModel.PhonePerPage);

            var phoneBrand = this.phones.AllPhoneBrands();

            query.TotalPhones = allPhones.TotalPhones;
            query.Brands = phoneBrand;
            query.Phones = allPhones.Phones;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myPhones = this.phones.ByUser(this.User.GetId());

            return View(myPhones);
        }

        public IActionResult Details(int id, string information)
        {
            var phone = this.phones.Details(id);

            if (information != phone.ToFriendlyUrl())
            {
                return BadRequest();
            }

            return View(phone);
        }


        [Authorize]
        public IActionResult Add()
        {
            if (!this.owners.IsOwner(this.User.GetId()))
            {
                return RedirectToAction("Create", "Owners");
            }

            return View(new PhoneFormModel
            {
                Categories = this.phones.AllCategories()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(PhoneFormModel phone)
        {
            var ownerId = this.owners.GetIdByUser(this.User.GetId());

            if (ownerId == 0)
            {
                return RedirectToAction("Create", "Owners");
            }

            if (!this.phones.CategoryExists(phone.CategoryId))
            {
                this.ModelState.AddModelError(nameof(phone.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                phone.Categories = this.phones.AllCategories();
                return View(phone);
            }

            var phoneId = this.phones.Create(phone.Brand,
                phone.Model,
                phone.ImageUrl,
                phone.Description,
                phone.PhoneNumber,
                phone.Year,
                phone.CategoryId,
                phone.PriceForPhone,
                ownerId);

            TempData[GlobalMessageKey] = "You phone was added and is awaiting for approval.";

            return RedirectToAction(nameof(Details), new { id = phoneId, information = phone.ToFriendlyUrl() });
        }


        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.owners.IsOwner(userId) && !User.IsAdmin())
            {
                return RedirectToAction("Create", "Owners");
            }

            var phone = this.phones.Details(id);

            if (phone.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var phoneForm = this.mapper.Map<PhoneFormModel>(phone);

            phoneForm.Categories = this.phones.AllCategories();

            return View(phoneForm);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, PhoneFormModel phone)
        {
            var ownerId = this.owners.GetIdByUser(this.User.GetId());

            if (ownerId == 0 && !User.IsAdmin())
            {
                return RedirectToAction("Create", "Owners");
            }

            if (!this.phones.CategoryExists(phone.CategoryId))
            {
                this.ModelState.AddModelError(nameof(phone.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                phone.Categories = this.phones.AllCategories();
                return View(phone);
            }

            if (!this.phones.IsByOwner(id, ownerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            var edited = this.phones.Edit(id,
               phone.Brand,
               phone.Model,
               phone.ImageUrl,
               phone.Description,
               phone.PhoneNumber,
               phone.Year,
               phone.CategoryId,
               phone.PriceForPhone,
               ownerId,
               this.User.IsAdmin());


            TempData[GlobalMessageKey] = $"You phone was edited{(this.User.IsAdmin() ? string.Empty : " and is awaiting for approval")}!";

            return RedirectToAction(nameof(Details), new { id, information = phone.ToFriendlyUrl() });
        }

        [Authorize]
        public IActionResult Delete(int id)
        {

            var userId = this.User.GetId();

            var phone = this.phones.Details(id);

            if (phone.UserId != userId)
            {
                return Unauthorized();
            }

            var phoneForm = this.mapper.Map<PhoneFormModel>(phone);

            phoneForm.Categories = this.phones.AllCategories();

            this.phones.Delete(id);
           
            return RedirectToAction("All");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id, PhoneFormModel phone)
        {
            var ownerId = this.owners.GetIdByUser(this.User.GetId());

            if (ownerId == 0 && !User.IsAdmin())
            {
                return RedirectToAction("Create", "Owners");
            }

            if (!this.phones.CategoryExists(phone.CategoryId))
            {
                this.ModelState.AddModelError(nameof(phone.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                phone.Categories = this.phones.AllCategories();
                return View(phone);
            }

            if (!this.phones.IsByOwner(id, ownerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.phones.Delete(id);


            TempData[GlobalMessageKey] = $"This phone was deleted!";

            return RedirectToAction("All");
        }
    }
}   

ShopPhone/Views/Home/Index.cshtml
@model List<LatestPhoneServiceModel>

@{
    ViewData["Title"] = "Welcome";
}

@if (!Model.Any())
{
    <div class="jumbotron">
        <h1 class="display-4">Welcome to best place for SmartPhones</h1>
        <p class="lead">There are no phones in the system now!</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
            <a asp-controller="Phones" asp-action="Add" class="btn btn-primary btn-lg">Add Phone</a>
        </p>
    </div>
}

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < Model.Count; i++)
        {
            var phone = Model[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
                <img class="d-block w-50" src="@phone.ImageUrl" alt="@phone.Brand @phone.Model">
                <div class="carousel-caption d-none d-md-block">
                    <h5><a class="btn btn-primary" asp-controller="Phones" asp-action="Details" asp-route-id="@phone.Id" asp-route-information="@phone.ToFriendlyUrl()">@phone.Year  @phone.Brand @phone.Model</a></h5>
                    <a class="adConnectButton adConnectButtonPhone" style="margin-top: 10px;" data-id="id" data-hash="1b7fbd8095eaca98d668b27e4f02db86" href="tel:0898 562 472">
                    <alt="">@phone.PhoneNumber "make orders"</a>
                </div>
            </div>
        }
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="md=5"></div>

@if (User.IsAdmin())
{
    <div class="row">
        <div class="col-12 text-center">
            <button class="btn btn-primary" id="statistics-button">Show Statistics</button>
        </div>
    </div>

    <div class="jumbotron d-none" id="statistics">
        <div class="row">
            <h2 class="col-md-4 text-center" id="total-phones"></h2>
            <h2 class="col-md-4 text-center" id="total-users"></h2>
            <h2 class="col-md-4 text-center" id="total-price"></h2>
        </div>
    </div>

    @section Scripts {
        <script>
            $('#statistics-button').on('click', ev => {
                $.get('/api/statistics', (data) => {
                    $('#total-phones').text(data.totalPhones + " Phones");
                    $('#total-users').text(data.totalUsers + " Users");
                    $('#total-price').text(data.totalPrice + " Price");


                    $('#statistics').removeClass('d-none');
                    $('#statistics-buton').hide();
                });
            })
        </script>
    }
}